// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hctxpsyjsvwerogoogyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjdHhwc3lqc3Z3ZXJvZ29vZ3lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNzAyMTYsImV4cCI6MjA3MTg0NjIxNn0.vOivqB4Khdh4G0dkku36JrC6ZwlWURC73PRaLYp7hSQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});